name: opencode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  opencode:
    if: |
      github.actor != 'chatgpt-codex-connector[bot]' &&
      (
        (
          github.event_name != 'pull_request_review' &&
          (
            contains(toLower(github.event.comment.body || ''), '/oc') ||
            contains(toLower(github.event.comment.body || ''), '/opencode') ||
            contains(toLower(github.event.comment.body || ''), '/or')
          )
        ) ||
        (
          github.event_name == 'pull_request_review' &&
          (
            contains(toLower(github.event.review.body || ''), '/oc') ||
            contains(toLower(github.event.review.body || ''), '/opencode') ||
            contains(toLower(github.event.review.body || ''), '/or')
          )
        )
      )
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run opencode
        uses: anomalyco/opencode/github@latest
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        with:
          model: openrouter/google/gemini-3.1-pro-preview-customtools
